name: ci

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout repo
        uses: actions/checkout@v4
      #  with:
      #    ref: main
      #-
      #  name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3
      
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            wsukduncan/s25cats
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
